version: '2'
services:
  dbms:
    container_name: rdbms
    build: 
        context: .
        dockerfile: database/Dockerfile
    ports:
     - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: root
  apim-traffic:
    container_name: apim-traffic
    depends_on: 
      - dbms
    build:
      context: .
      dockerfile: apim-traffic/Dockerfile
  apim-keymanager:
    container_name: apim-keymanager
    depends_on: 
      - dbms
    build:
      context: .
      dockerfile: apim-keymanager/Dockerfile
  apim-gateway:
    container_name: apim-gateway
    depends_on: 
      - dbms
    build:
      context: .
      dockerfile: apim-gateway/Dockerfile
    ports:
      - "8280:8280"
      - "8243:8243"
  apim-publisher:
    container_name: apim-publisher
    depends_on: 
      - dbms
    build:
      context: .
      dockerfile: apim-publisher/Dockerfile
    ports:
      - "9763:9763"
      - "9443:9443"
  apim-store:
    container_name: apim-store
    depends_on: 
      - dbms
    build:
      context: .
      dockerfile: apim-store/Dockerfile
    ports:
      - "9764:9764"
      - "9444:9444"